targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
          explicit_to_json: true
#flutter pub run build_runner build --delete-conflicting-outputs
