name: flutter_social_auth
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  app_links: ^3.4.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter:
    sdk: flutter
  icons_plus: ^3.0.0
  json_annotation: null
  provider: ^6.0.5
  routemaster: ^1.0.1
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  url_protocol: ^1.0.0
  url_strategy: ^0.2.0
  win32_registry: ^1.0.2

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: null

flutter:
  uses-material-design: true
